### ISSUE TITLE
Parallel Run feature is not working with CITS1.2 and older version too

### ISSUE THREAD

**Issue by CallKrish** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter-Helpdoc#16]
Hi, I tried to perform execution using Parallel run, however CITS executed all test cases one by one. Please help to clarify or fix the issue.
The generated report   shows with parallel count even its perform execution in single browser. 

My Test Env: 
Solution: CITS 1.2
Browser: IE 11
Tool used: Selenium

**Comment by Shantha93** [comment]
There are known issues with performing parallel execution in IE using Selenium Webdriver. Please search more on wider audience forums in the internet and you will end up with a plenty of known issues with IEdrivers behaviour. 

Hence this is not a bug report. 

Please post any queries going forward in google groups forum,
https://groups.google.com/forum/#!forum/cognizant-intelligent-test-scripter
